# first, give the workflow a name
name: hello-world-msg

# next, define when the workflow should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

# define the jobs that the workflow should run
jobs:
  build:
    runs-on: ubuntu-latest

    # steps that the job will run
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a hello world message
      run: echo "Hello, world!"
  goodluck:
    runs-on: ubuntu-24.04
    steps:
        - name: print a goodluck message
          run: echo "Goodluck!"

  # lint for go code
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        run: golangci-lint run

  # test for go code
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./...

  # scan with semgrep
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan with Semgrep
        run: docker run --rm -v ${{ github.workspace }}:/src returntocorp/semgrep --config=p/r2c-ci