on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config=p/security-audit --json --output=semgrep_results.json codegen/
        continue-on-error: true

      - name: Analyze Semgrep Results
        if: always()
        run: |
          if jq -e '.results | length > 0' semgrep_results.json > /dev/null; then
            echo "::error::Semgrep found security issues"
            echo "SCAN_FAILED=true" >> $GITHUB_ENV
          fi

rules:
  - id: insecure-http
    patterns:
      - pattern: http.Get(...)
    message: "Use HTTPS instead of HTTP for secure communication."
    languages: [go]
    severity: ERROR

  - id: sql-injection
    patterns:
      - pattern: db.Exec(...)
    message: "Potential SQL injection vulnerability."
    languages: [go]
    severity: ERROR

  - id: hardcoded-secret
    patterns:
      - pattern: "... = '...'"
    message: "Hardcoded secret detected."
    languages: [go]
    severity: ERROR

  - id: command-injection
    patterns:
      - pattern: exec.Command(...)
    message: "Potential command injection vulnerability."
    languages: [go]
    severity: ERROR

  - id: insecure-random
    patterns:
      - pattern: rand.Int(...)
    message: "Use crypto/rand for secure random number generation."
    languages: [go]
    severity: ERROR

  - id: insecure-deserialization
    patterns:
      - pattern: gob.NewDecoder(...)
    message: "Insecure deserialization detected."
    languages: [go]
    severity: ERROR

  - id: insecure-file-permissions
    patterns:
      - pattern: os.OpenFile(..., 0666)
    message: "Insecure file permissions detected."
    languages: [go]
    severity: ERROR

  - id: insecure-env-var
    patterns:
      - pattern: os.Getenv(...)
    message: "Insecure environment variable usage detected."
    languages: [go]
    severity: ERROR

  - id: insecure-http-client
    patterns:
      - pattern: http.NewRequest(...)
    message: "Insecure HTTP client usage detected."
    languages: [go]
    severity: ERROR